apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ptorder
  labels:
    app: Ptorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Ptorder
  template:
    metadata:
      labels:
        app: Ptorder
    spec:
      containers:
        - name: Ptorder
          image: username/Ptorder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5