apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pttrainer
  labels:
    app: Pttrainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Pttrainer
  template:
    metadata:
      labels:
        app: Pttrainer
    spec:
      containers:
        - name: Pttrainer
          image: username/Pttrainer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5