apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptPay
  labels:
    app: ptPay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptPay
  template:
    metadata:
      labels:
        app: ptPay
    spec:
      containers:
        - name: ptPay
          image: username/ptPay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5