apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptTicket
  labels:
    app: ptTicket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptTicket
  template:
    metadata:
      labels:
        app: ptTicket
    spec:
      containers:
        - name: ptTicket
          image: username/ptTicket:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5