apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptTicketManager
  labels:
    app: ptTicketManager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptTicketManager
  template:
    metadata:
      labels:
        app: ptTicketManager
    spec:
      containers:
        - name: ptTicketManager
          image: username/ptTicketManager:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5